#!/bin/sh

case "$1" in
    start)
        echo "Starting aesdsocket"
        start-stop-daemon -S -b -n aesdsocket -x /usr/bin/aesdsocket -- -d
        ;;
    stop)
        echo "Stopping aesdsocket"
        start-stop-daemon -K -x aesdsocket
        ;;
    *)
        echo "Usage $0 {start|stop}"
    exit 1
esac
exit 0
